In [52]:
import pandas as pd
import numpy as np

weatherDf = pd.read_csv("weather_data.csv", encoding='cp949')

# 전처리 (필요없는 항목 필터링)
weatherDf = weatherDf[['지점명', "일시", '기온(°C)']]

In [53]:
#전처리2-1 (필요한 카테고리 선택)
is_seoul = weatherDf["지점명"] == "서울"
seoul = weatherDf[is_seoul]
seoul

     지점명                일시  기온(°C)
0     서울  2020-01-01 00:00    -6.5
1     서울  2020-01-01 01:00    -5.9
2     서울  2020-01-01 02:00    -5.7
3     서울  2020-01-01 03:00    -5.6
4     서울  2020-01-01 04:00    -5.4
...   ..               ...     ...
8778  서울  2020-12-31 19:00    -7.1
8779  서울  2020-12-31 20:00    -7.1
8780  서울  2020-12-31 21:00    -7.2
8781  서울  2020-12-31 22:00    -7.4
8782  서울  2020-12-31 23:00    -7.6

[8783 rows x 3 columns]

In [54]:
#전처리2-2
is_busan = weatherDf["지점명"] == "부산"
busan = weatherDf[is_busan]
busan

      지점명                일시  기온(°C)
8783   부산  2020-01-01 00:00    -2.5
8784   부산  2020-01-01 01:00    -2.9
8785   부산  2020-01-01 02:00    -3.1
8786   부산  2020-01-01 03:00    -2.8
8787   부산  2020-01-01 04:00    -3.1
...    ..               ...     ...
17557  부산  2020-12-31 19:00     0.6
17558  부산  2020-12-31 20:00     0.1
17559  부산  2020-12-31 21:00    -0.2
17560  부산  2020-12-31 22:00    -0.7
17561  부산  2020-12-31 23:00    -0.7

[8779 rows x 3 columns]

In [133]:
#전처리3  (누락된 항목 갯수 일치시키기)

# 서울
temp = []
for date in seoul["일시"]:
    temp.append(date.split(" ")[0]) # '날짜 시간'형태의 자료를 " "공백으로 잘라서 날짜만 [0]인덱스로 append
temp_seoul = []
unique_temp = set(temp) #set 자료형으로 형변환하여 중복자료 제거


for date in unique_temp:
    if temp.count(date) != 24:
        temp_seoul.append(date) # 누락된 데이터 찾기 (8월 26일)

timeNp = np.arange(24)
findTime = []
full_date = []
result = []

# 8월 26일 중 누락된 시간 찾기
for date in seoul["일시"]: 
    for temp_date in temp_seoul:
        if(temp_date in date):
            findTime.append(date.split(" ")[1])



# 누락된 시간만 정제
for i in range(len(temp_seoul)):
    strArray2 =[]
    for j in timeNp:
        full_date.append(temp_seoul[i] + " " + str(j).zfill(2)+ ":00")

    for j in range(len(findTime)):
        strArray2.append(temp_seoul[i] + " " + findTime[j])

    for j in timeNp:
        if full_date[j] != strArray2[j]:
            result.append(full_date[j])
            strArray2.insert(j, full_date[j])

print(result)

['2020-08-26 13:00']

In [132]:
# 부산
temp = []
for date in busan["일시"]:
    temp.append(date.split(" ")[0])
temp_busan = []
unique_temp = set(temp)


for date in unique_temp:
    if temp.count(date) != 24:
        temp_busan.append(date)

timeNp = np.arange(24)
findTime = []
full_date = []
result = []


for date in busan["일시"]: 
    for temp_date in temp_busan:
        if(temp_date in date):
            findTime.append(date.split(" ")[1])
            

# 누락된 시간만 정제
for i in range(len(temp_busan)):
    strArray2 =[]
    for j in timeNp:
        full_date.append(temp_busan[i] + " " + str(j).zfill(2)+ ":00")

    for j in range(len(findTime)):
        strArray2.append(temp_busan[i] + " " + findTime[j])

    for j in timeNp:
        if full_date[j] != strArray2[j]:
            result.append(full_date[j])
            strArray2.insert(j, full_date[j])

print(result)

['2020-08-26 04:00', '2020-08-26 06:00', '2020-08-26 14:00', '2020-08-26 15:00', '2020-08-26 21:00']